import { Registry } from "@/registry/schema";

export const ui: Registry = [
  {
    name: "canvas-button",
    type: "registry:ui",
    dependencies: ["framer-motion", "class-variance-authority"],
    files: ["xanthic/canvas-button.tsx"],
    registryDependencies: [],
  },
  {
    name: "color-palette",
    type: "registry:ui",
    dependencies: ["class-variance-authority"],
    files: ["xanthic/color-palette.tsx"],
  },
  {
    name: "sketch-input",
    type: "registry:ui",
    dependencies: ["framer-motion", "class-variance-authority"],
    files: ["xanthic/sketch-input.tsx"],
    registryDependencies: [],
  },
  {
    name: "gallery-grid",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["xanthic/gallery-grid.tsx"],
  },
  {
    name: "easel-tabs",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-tabs", "framer-motion"],
    files: ["xanthic/easel-tabs.tsx"],
  },
  {
    name: "palette-navigation",
    type: "registry:ui",
    dependencies: ["framer-motion", "lucide-react"],
    files: ["xanthic/palette-navigation.tsx"],
  },
  {
    name: "canvas-modal",
    type: "registry:ui",
    dependencies: ["framer-motion", "@radix-ui/react-dialog", "lucide-react"],
    files: ["xanthic/canvas-modal.tsx"],
  },
  {
    name: "brush-stroke-loader",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["xanthic/brush-stroke-loader.tsx"],
  },
  {
    name: "canvas-slider",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-slider", "framer-motion"],
    files: ["xanthic/canvas-slider.tsx"],
  },
  {
    name: "art-board-layout",
    type: "registry:ui",
    dependencies: ["@dnd-kit/core"],
    files: ["xanthic/art-board-layout.tsx"],
  },
  {
    name: "palette-toast",
    type: "registry:ui",
    dependencies: [],
    files: ["xanthic/palette-toast.tsx"],
    registryDependencies: [],
  },
  {
    name: "canvas-drawer",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["xanthic/canvas-drawer.tsx"],
  },
  {
    name: "texture-overlay",
    type: "registry:ui",
    dependencies: [],
    files: ["xanthic/texture-overlay.tsx"],
  },
  {
    name: "canvas-color-picker",
    type: "registry:ui",
    dependencies: ["lucide-react"],
    files: ["xanthic/canvas-color-picker.tsx"],
  },
  {
    name: "canvas-grid",
    type: "registry:ui",
    dependencies: ["lucide-react"],
    files: ["xanthic/canvas-grid.tsx"],
  },
  {
    name: "artistic-navigation",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["xanthic/artistic-navigation.tsx"],
  },
  {
    name: "canvas-dock",
    type: "registry:ui",
    dependencies: ["framer-motion", "next-themes"],
    files: ["xanthic/canvas-dock.tsx"],
  },
  {
    name: "studio-light",
    type: "registry:ui",
    dependencies: ["framer-motion", "next-themes"],
    files: ["xanthic/studio-light.tsx"],
  },
  {
    name: "sketch-accordion",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-accordion"],
    files: ["xanthic/sketch-accordion.tsx"],
  },
  {
    name: "canvas-menu",
    type: "registry:ui",
    registryDependencies: ["@radix-ui/react-menu"],
    files: ["xanthic/canvas-menu.tsx"],
  },
  {
    name: "ink-alert",
    type: "registry:ui",
    dependencies: ["class-variance-authority", "lucide-react"],
    files: ["xanthic/ink-alert.tsx"],
  },
  {
    name: "artistic-tooltip",
    type: "registry:ui",
    dependencies: ["class-variance-authority"],
    files: ["xanthic/artistic-tooltip.tsx"],
  },
  {
    name: "canvas-annotations",
    type: "registry:ui",
    dependencies: [],
    files: ["xanthic/canvas-annotations.tsx"],
  },
  {
    name: "layer-manager",
    type: "registry:ui",
    dependencies: ["lucide-react"],
    files: ["xanthic/layer-manager.tsx"],
  },
  {
    name: "texture-browser",
    type: "registry:ui",
    dependencies: ["lucide-react"],
    files: ["xanthic/texture-browser.tsx"],
  },
  {
    name: "color-scheme-generator",
    type: "registry:ui",
    dependencies: ["lucide-react"],
    files: ["xanthic/color-scheme-generator.tsx"],
  },
  {
    name: "art-board-presets",
    type: "registry:ui",
    dependencies: ["lucide-react"],
    files: ["xanthic/art-board-presets.tsx"],
  },
  {
    name: "canvas-timeline",
    type: "registry:ui",
    dependencies: ["lucide-react"],
    files: ["xanthic/canvas-timeline.tsx"],
  },
  {
    name: "artistic-data-viz",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["xanthic/artistic-data-viz.tsx"],
  },
  {
    name: "artistic-statistics-card",
    type: "registry:ui",
    files: ["xanthic/artistic-statistics-card.tsx"],
    dependencies: [],
  },
  {
    name: "stepper",
    type: "registry:ui",
    dependencies: ["class-variance-authority"],
    files: ["xanthic/stepper.tsx"],
    registryDependencies: ["button"],
  },
  {
    name: "studio-pagination",
    type: "registry:ui",
    dependencies: ["lucide-react"],
    files: ["xanthic/studio-pagination.tsx"],
  },
  {
    name: "collapsible-card",
    type: "registry:ui",
    dependencies: ["lucide-react", "framer-motion"],
    files: ["xanthic/collapsible-card.tsx"],
  },
  {
    name: "gallery-flow",
    type: "registry:ui",
    dependencies: ["lucide-react", "framer-motion"],
    files: ["xanthic/gallery-flow.tsx"],
  },
  {
    name: "studio-shortcuts-guide",
    type: "registry:ui",
    dependencies: ["lucide-react", "framer-motion"],
    files: ["xanthic/studio-shortcuts-guide.tsx"],
  },
  {
    name: "creative-otp-input",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["xanthic/creative-otp-input.tsx"],
  },
  {
    name: "creative-clipboard-actions",
    type: "registry:ui",
    dependencies: ["framer-motion", "lucide-react"],
    files: ["xanthic/creative-clipboard-actions.tsx"],
  },
  {
    name: "studio-share-module",
    type: "registry:ui",
    dependencies: ["framer-motion", "lucide-react", "qrcode.react"],
    files: ["xanthic/studio-share-module.tsx"],
  },
  {
    name: "artistic-settings-panel",
    type: "registry:ui",
    dependencies: ["framer-motion", "lucide-react"],
    files: ["xanthic/artistic-settings-panel.tsx"],
  },
  {
    name: "creative-code-display",
    type: "registry:ui",
    dependencies: ["framer-motion", "next-themes", "prismjs"],
    files: ["xanthic/creative-code-display.tsx"],
  },
  {
    name: "sketch-calendar-picker",
    type: "registry:ui",
    dependencies: ["framer-motion", "date-fns", "lucide-react"],
    files: ["xanthic/sketch-calendar-picker.tsx"],
  },
  {
    name: "texture-blend-transitions",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["xanthic/texture-blend-transitions.tsx"],
  },
  {
    name: "artistic-cursor-effects",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["xanthic/artistic-cursor-effects.tsx"],
  },
  {
    name: "canvas-voice-commander",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["xanthic/canvas-voice-commander.tsx"],
  },
  {
    name: "creative-error-boundaries",
    type: "registry:ui",
    dependencies: ["framer-motion", "lucide-react"],
    files: ["xanthic/creative-error-boundaries.tsx"],
  },
  {
    name: "billing-history-timeline",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["xanthic/billing-history-timeline.tsx"],
  },
  {
    name: "gradient-mesh-background",
    type: "registry:ui",
    dependencies: [],
    files: ["xanthic/gradient-mesh-background.tsx"],
  },
  {
    name: "grid-pattern-background",
    type: "registry:ui",
    dependencies: [],
    files: ["xanthic/grid-pattern-background.tsx"],
  },
  {
    name: "particle-background",
    type: "registry:ui",
    dependencies: [],
    files: ["xanthic/particle-background.tsx"],
  },
];
