import { Registry } from "@/registry/schema";

export const examples: Registry = [
  {
    name: "cosmic-scene-demo",
    type: "registry:example",
    files: ["example/cosmic-scene-demo.tsx"],
    registryDependencies: ["cosmic-scene"],
  },
  {
    name: "sketch-input-demo",
    type: "registry:example",
    registryDependencies: ["sketch-input"],
    files: ["example/sketch-input-demo.tsx"],
  },
  {
    name: "easel-tabs-demo",
    type: "registry:example",
    registryDependencies: ["easel-tabs"],
    files: ["example/easel-tabs-demo.tsx"],
  },
  {
    name: "palette-navigation-demo",
    type: "registry:example",
    registryDependencies: ["palette-navigation"],
    files: ["example/palette-navigation-demo.tsx"],
  },
  {
    name: "canvas-modal-demo",
    type: "registry:example",
    registryDependencies: ["canvas-modal"],
    files: ["example/canvas-modal-demo.tsx"],
  },
  {
    name: "brush-stroke-loader-demo",
    type: "registry:example",
    registryDependencies: ["brush-stroke-loader"],
    files: ["example/brush-stroke-loader-demo.tsx"],
  },
  {
    name: "art-board-layout-demo",
    type: "registry:example",
    registryDependencies: ["art-board-layout"],
    files: ["example/art-board-layout-demo.tsx"],
  },
  {
    name: "palette-toast-demo",
    type: "registry:example",
    registryDependencies: ["palette-toast", "button"],
    files: ["example/palette-toast-demo.tsx"],
  },
  {
    name: "canvas-drawer-demo",
    type: "registry:example",
    registryDependencies: ["canvas-drawer", "button"],
    files: ["example/canvas-drawer-demo.tsx"],
  },
  {
    name: "canvas-grid-demo",
    type: "registry:example",
    registryDependencies: ["canvas-grid"],
    files: ["example/canvas-grid-demo.tsx"],
  },
  {
    name: "artistic-navigation-demo",
    type: "registry:example",
    registryDependencies: ["artistic-navigation"],
    files: ["example/artistic-navigation-demo.tsx"],
  },
  {
    name: "smart-dock-demo",
    type: "registry:example",
    registryDependencies: ["smart-dock"],
    files: ["example/smart-dock-demo.tsx"],
  },
  {
    name: "sketch-accordion-demo",
    type: "registry:example",
    registryDependencies: ["sketch-accordion"],
    files: ["example/sketch-accordion-demo.tsx"],
  },
  {
    name: "canvas-menu-demo",
    type: "registry:example",
    registryDependencies: ["canvas-menu"],
    files: ["example/canvas-menu-demo.tsx"],
  },
  {
    name: "artistic-tooltip-demo",
    type: "registry:example",
    registryDependencies: ["artistic-tooltip"],
    files: ["example/artistic-tooltip-demo.tsx"],
  },
  {
    name: "canvas-annotations-demo",
    type: "registry:example",
    registryDependencies: ["canvas-annotations"],
    files: ["example/canvas-annotations-demo.tsx"],
  },
  {
    name: "layer-manager-demo",
    type: "registry:example",
    registryDependencies: ["layer-manager"],
    files: ["example/layer-manager-demo.tsx"],
  },
  {
    name: "texture-browser-demo",
    type: "registry:example",
    registryDependencies: ["texture-browser"],
    files: ["example/texture-browser-demo.tsx"],
  },
  {
    name: "art-board-presets-demo",
    type: "registry:example",
    registryDependencies: ["art-board-presets"],
    files: ["example/art-board-presets-demo.tsx"],
  },
  {
    name: "canvas-timeline-demo",
    type: "registry:example",
    registryDependencies: ["canvas-timeline"],
    files: ["example/canvas-timeline-demo.tsx"],
  },
  {
    name: "artistic-data-viz-demo",
    type: "registry:example",
    registryDependencies: ["artistic-data-viz"],
    files: ["example/artistic-data-viz-demo.tsx"],
  },
  {
    name: "collapsible-card-demo",
    type: "registry:example",
    registryDependencies: ["collapsible-card"],
    files: ["example/collapsible-card-demo.tsx"],
  },
  {
    name: "gallery-flow-demo",
    type: "registry:example",
    registryDependencies: ["gallery-flow"],
    files: ["example/gallery-flow-demo.tsx"],
  },
  {
    name: "studio-shortcuts-guide-demo",
    type: "registry:example",
    registryDependencies: ["studio-shortcuts-guide"],
    files: ["example/studio-shortcuts-guide-demo.tsx"],
  },
  {
    name: "creative-otp-input-demo",
    type: "registry:example",
    registryDependencies: ["creative-otp-input"],
    files: ["example/creative-otp-input-demo.tsx"],
  },
  {
    name: "creative-clipboard-actions-demo",
    type: "registry:example",
    registryDependencies: ["creative-clipboard-actions"],
    files: ["example/creative-clipboard-actions-demo.tsx"],
  },
  {
    name: "creative-code-display-demo",
    type: "registry:example",
    registryDependencies: ["creative-code-display"],
    files: ["example/creative-code-display-demo.tsx"],
  },
  {
    name: "sketch-calendar-picker-demo",
    type: "registry:example",
    registryDependencies: ["sketch-calendar-picker"],
    files: ["example/sketch-calendar-picker-demo.tsx"],
  },
  {
    name: "texture-blend-transitions-demo",
    type: "registry:example",
    registryDependencies: ["texture-blend-transitions"],
    files: ["example/texture-blend-transitions-demo.tsx"],
  },
  {
    name: "artistic-cursor-effects-demo",
    type: "registry:example",
    registryDependencies: ["artistic-cursor-effects"],
    files: ["example/artistic-cursor-effects-demo.tsx"],
  },
  {
    name: "canvas-voice-commander-demo",
    type: "registry:example",
    registryDependencies: ["canvas-voice-commander"],
    files: ["example/canvas-voice-commander-demo.tsx"],
  },
  {
    name: "creative-error-boundaries-demo",
    type: "registry:example",
    registryDependencies: ["creative-error-boundaries"],
    files: ["example/creative-error-boundaries-demo.tsx"],
  },
  {
    name: "gradient-mesh-background-demo",
    type: "registry:example",
    registryDependencies: ["gradient-mesh-background"],
    files: ["example/gradient-mesh-background-demo.tsx"],
  },
  {
    name: "grid-pattern-background-demo",
    type: "registry:example",
    registryDependencies: ["grid-pattern-background"],
    files: ["example/grid-pattern-background-demo.tsx"],
  },
  {
    name: "particle-background-demo",
    type: "registry:example",
    registryDependencies: ["particle-background"],
    files: ["example/particle-background-demo.tsx"],
  },
  {
    name: "climate-artboard-demo",
    type: "registry:example",
    registryDependencies: ["climate-artboard"],
    files: ["example/climate-artboard-demo.tsx"],
  },
  {
    name: "stacked-carousel-demo",
    type: "registry:example",
    registryDependencies: ["stacked-carousel"],
    files: ["example/stacked-carousel-demo.tsx"],
  },
  {
    name: "expand-image-demo",
    type: "registry:example",
    registryDependencies: ["expand-image"],
    files: ["example/expand-image-demo.tsx"],
  },
  {
    name: "neumorphism-loader-demo",
    type: "registry:example",
    registryDependencies: ["neumorphism-loader"],
    files: ["example/neumorphism-loader-demo.tsx"],
  },
  {
    name: "swarm-effect-demo",
    type: "registry:example",
    registryDependencies: ["swarm-effect"],
    files: ["example/swarm-effect-demo.tsx"],
  },
  {
    name: "mesh-matrix-demo",
    type: "registry:example",
    registryDependencies: ["mesh-matrix"],
    files: ["example/mesh-matrix-demo.tsx"],
  },
  {
    name: "blob-background-demo",
    type: "registry:example",
    registryDependencies: ["blob-background"],
    files: ["example/blob-background-demo.tsx"],
  },
  {
    name: "starfall-demo",
    type: "registry:example",
    registryDependencies: ["starfall"],
    files: ["example/starfall-demo.tsx"],
  },
  {
    name: "beam-portal-demo",
    type: "registry:example",
    registryDependencies: ["beam-portal"],
    files: ["example/beam-portal-demo.tsx"],
  },
  {
    name: "pulse-card-demo",
    type: "registry:example",
    registryDependencies: ["pulse-card"],
    files: ["example/pulse-card-demo.tsx"],
  },
  {
    name: "ghost-text-demo",
    type: "registry:example",
    registryDependencies: ["ghost-text"],
    files: ["example/ghost-text-demo.tsx"],
  },
  {
    name: "infinite-scroll-demo",
    type: "registry:example",
    registryDependencies: ["infinite-scroll"],
    files: ["example/infinite-scroll-demo.tsx"],
  },
  {
    name: "blur-gallery-demo",
    type: "registry:example",
    registryDependencies: ["blur-gallery"],
    files: ["example/blur-gallery-demo.tsx"],
  },
  {
    name: "circuit-pulse-demo",
    type: "registry:example",
    registryDependencies: ["circuit-pulse"],
    files: ["example/circuit-pulse-demo.tsx"],
  },
  {
    name: "neon-button-demo",
    type: "registry:example",
    registryDependencies: ["neon-button"],
    files: ["example/neon-button-demo.tsx"],
  },
  {
    name: "three-d-card-demo",
    type: "registry:example",
    registryDependencies: ["three-d-card"],
    files: ["example/three-d-card-demo.tsx"],
  },
  {
    name: "swipe-cards-demo",
    type: "registry:example",
    registryDependencies: ["swipe-cards"],
    files: ["example/swipe-cards-demo.tsx"],
  },
  {
    name: "motion-text-demo",
    type: "registry:example",
    registryDependencies: ["motion-text"],
    files: ["example/motion-text-demo.tsx"],
  },
  {
    name: "magnetic-card-demo",
    type: "registry:example",
    registryDependencies: ["magnetic-card"],
    files: ["example/magnetic-card-demo.tsx"],
  },
  {
    name: "spotlight-card-demo",
    type: "registry:example",
    registryDependencies: ["spotlight-card"],
    files: ["example/spotlight-card-demo.tsx"],
  },
  {
    name: "holographic-card-demo",
    type: "registry:example",
    registryDependencies: ["holographic-card"],
    files: ["example/holographic-card-demo.tsx"],
  },
  {
    name: "typewriter-hero-demo",
    type: "registry:example",
    registryDependencies: ["typewriter-hero"],
    files: ["example/typewriter-hero-demo.tsx"],
  },
  {
    name: "floating-navbar-demo",
    type: "registry:example",
    registryDependencies: ["floating-navbar"],
    files: ["example/floating-navbar-demo.tsx"],
  },
  {
    name: "particle-veil-demo",
    type: "registry:example",
    registryDependencies: ["particle-veil"],
    files: ["example/particle-veil-demo.tsx"],
  },
];
