// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "canvas-button": {
      name: "canvas-button",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui-canvas/canvas-button.tsx"],
      component: React.lazy(() => import("@/registry/default/ui-canvas/canvas-button.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "color-palette": {
      name: "color-palette",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui-canvas/color-palette.tsx"],
      component: React.lazy(() => import("@/registry/default/ui-canvas/color-palette.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sketch-input": {
      name: "sketch-input",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui-canvas/sketch-input.tsx"],
      component: React.lazy(() => import("@/registry/default/ui-canvas/sketch-input.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "gallery-grid": {
      name: "gallery-grid",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui-canvas/gallery-grid.tsx"],
      component: React.lazy(() => import("@/registry/default/ui-canvas/gallery-grid.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "easel-tabs": {
      name: "easel-tabs",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui-canvas/easel-tabs.tsx"],
      component: React.lazy(() => import("@/registry/default/ui-canvas/easel-tabs.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "palette-navigation": {
      name: "palette-navigation",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui-canvas/palette-navigation.tsx"],
      component: React.lazy(() => import("@/registry/default/ui-canvas/palette-navigation.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "canvas-modal": {
      name: "canvas-modal",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui-canvas/canvas-modal.tsx"],
      component: React.lazy(() => import("@/registry/default/ui-canvas/canvas-modal.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "brush-stroke-loader": {
      name: "brush-stroke-loader",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui-canvas/brush-stroke-loader.tsx"],
      component: React.lazy(() => import("@/registry/default/ui-canvas/brush-stroke-loader.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "art-board-layout": {
      name: "art-board-layout",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui-canvas/art-board-layout.tsx"],
      component: React.lazy(() => import("@/registry/default/ui-canvas/art-board-layout.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "palette-toast": {
      name: "palette-toast",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui-canvas/palette-toast.tsx"],
      component: React.lazy(() => import("@/registry/default/ui-canvas/palette-toast.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "color-palette-demo": {
      name: "color-palette-demo",
      type: "registry:example",
      registryDependencies: ["color-palette"],
      files: ["registry/default/example/color-palette-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/color-palette-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "canvas-button-demo": {
      name: "canvas-button-demo",
      type: "registry:example",
      registryDependencies: ["canvas-button"],
      files: ["registry/default/example/canvas-button-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/canvas-button-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sketch-input-demo": {
      name: "sketch-input-demo",
      type: "registry:example",
      registryDependencies: ["sketch-input"],
      files: ["registry/default/example/sketch-input-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/sketch-input-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "gallery-grid-demo": {
      name: "gallery-grid-demo",
      type: "registry:example",
      registryDependencies: ["gallery-grid"],
      files: ["registry/default/example/gallery-grid-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/gallery-grid-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "easel-tabs-demo": {
      name: "easel-tabs-demo",
      type: "registry:example",
      registryDependencies: ["easel-tabs"],
      files: ["registry/default/example/easel-tabs-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/easel-tabs-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "palette-navigation-demo": {
      name: "palette-navigation-demo",
      type: "registry:example",
      registryDependencies: ["palette-navigation"],
      files: ["registry/default/example/palette-navigation-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/palette-navigation-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "canvas-modal-demo": {
      name: "canvas-modal-demo",
      type: "registry:example",
      registryDependencies: ["canvas-modal"],
      files: ["registry/default/example/canvas-modal-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/canvas-modal-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "brush-stroke-loader-demo": {
      name: "brush-stroke-loader-demo",
      type: "registry:example",
      registryDependencies: ["brush-stroke-loader"],
      files: ["registry/default/example/brush-stroke-loader-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/brush-stroke-loader-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "art-board-layout-demo": {
      name: "art-board-layout-demo",
      type: "registry:example",
      registryDependencies: ["art-board-layout"],
      files: ["registry/default/example/art-board-layout-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/art-board-layout-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "palette-toast-demo": {
      name: "palette-toast-demo",
      type: "registry:example",
      registryDependencies: ["palette-toast","button"],
      files: ["registry/default/example/palette-toast-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/palette-toast-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
