// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "canvas-button": {
      name: "canvas-button",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui-canvas/canvas-button.tsx"],
      component: React.lazy(() => import("@/registry/default/ui-canvas/canvas-button.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "color-palette": {
      name: "color-palette",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui-canvas/color-palette.tsx"],
      component: React.lazy(() => import("@/registry/default/ui-canvas/color-palette.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sketch-input": {
      name: "sketch-input",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui-canvas/sketch-input.tsx"],
      component: React.lazy(() => import("@/registry/default/ui-canvas/sketch-input.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "color-palette-demo": {
      name: "color-palette-demo",
      type: "registry:example",
      registryDependencies: ["color-palette"],
      files: ["registry/default/example/color-palette-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/color-palette-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "canvas-button-demo": {
      name: "canvas-button-demo",
      type: "registry:example",
      registryDependencies: ["canvas-button"],
      files: ["registry/default/example/canvas-button-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/canvas-button-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sketch-input-demo": {
      name: "sketch-input-demo",
      type: "registry:example",
      registryDependencies: ["sketch-input"],
      files: ["registry/default/example/sketch-input-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/sketch-input-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
